services:
  backend:
    build: ./services/backend
    command: sh -c "npm install && npm run dev"
    working_dir: /app
    ports:
      - 3000:3000
    depends_on:
      - db
    volumes:
      - ./services/backend:/app
      - /app/node_modules
    environment:
      - PORT=3000
      - NODE_ENV=development
      - MONGODB_DSN=mongodb://db:27017/vteam-dev
      - GOOGLE_CLIENT_ID=72229994044-c79ferugmuftta95ms4kk1fdffk58a9u.apps.googleusercontent.com
      - GOOGLE_CLIENT_SECRET=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
      - GITHUB_CLIENT_ID=Ov23lilGKVWwk2B0alrl
      - GITHUB_CLIENT_SECRET=961c4c0950b8776da358ddd50b9049df5bbd4f73
      - GITHUB_REDIRECT_URI=http://localhost:3000/api/auth/github/callback
      - GOOGLE_REDIRECT_URI=http://localhost:3000/api/auth/google/callback
      - FRONTEND_OAUTH_REDIRECT=http://localhost:8080/oauth/callback
      - JWT_SECRET=hejsanhoppsan
      - STRIPE_PUBLISHABLE_KEY=pk_test_51ScB6U1SvvBu8btHmI7IH5j4j5Yeo3b8d7pNq2niIHVxBFk3X2yRTRYr2CZPOHWpWykLJgIbVNUWE4BO6ImzH413001zQAFdJg
      - STRIPE_SECRET_KEY=sk_test_51ScB6U1SvvBu8btHrQZkwdC2SSIYkWTnotcN8y2xfZYo9SG291VuAd7v2Z5h0TOEMuqCjMjCdIOtdaKt1bK4lbrc00l8OzKGi6
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://localhost:3000/health || exit 1"]
      interval: 5s
      timeout: 2s
      retries: 20
      start_period: 10s

  frontend:
    build: ./services/frontend
    command: sh -c "npm install && npm run dev"
    working_dir: /app
    ports:
      - 8080:3000
    depends_on:
      backend:
        condition: service_healthy

    volumes:
      - ./services/frontend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - API_URL_INTERNAL=http://backend:3000
      - NEXT_PUBLIC_API_URL=http://localhost:3000
      - NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY=pk_test_51ScB6U1SvvBu8btHmI7IH5j4j5Yeo3b8d7pNq2niIHVxBFk3X2yRTRYr2CZPOHWpWykLJgIbVNUWE4BO6ImzH413001zQAFdJg

  db:
    image: mongo:latest
    restart: unless-stopped
    volumes:
      - ./data/db:/data/db
    ports:
      - 27017:27017
    command: mongod --bind_ip_all
    environment:
      - MONGO_DATA_DIR=/data/db
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "mongosh --quiet --eval 'db.runCommand({ ping: 1 }).ok' || exit 1",
        ]
      interval: 5s
      timeout: 3s
      retries: 30
      start_period: 10s

  simulator:
    build:
      context: .
      dockerfile: services/scooter-simulator/Dockerfile
    depends_on:
      db:
        condition: service_healthy
      backend:
        condition: service_healthy
    environment:
      - NUMBER_OF_SCOOTERS=10
      - MONGODB_DSN=mongodb://db:27017/vteam-dev
      - BACKEND_BASE_URL=http://backend:3000
      - ROUTE_PROVIDER_API_URL=
      - ROUTE_PROVIDER_API_KEY=
    restart: "no"
