services:
  backend:
    build: ./services/backend
    command: sh -c "npm install && npm run dev"
    working_dir: /app
    ports:
      - 3000:3000
    depends_on:
      - db
    volumes:
      - ./services/backend:/app
      - /app/node_modules
    environment:
      - PORT=3000
      - NODE_ENV=development
      - MONGODB_DSN=mongodb://db:27017/vteam-dev
      - GOOGLE_CLIENT_ID=72229994044-c79ferugmuftta95ms4kk1fdffk58a9u.apps.googleusercontent.com
      - GOOGLE_CLIENT_SECRET=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
      - GOOGLE_REDIRECT_URI=http://localhost:3000/api/auth/google/callback
      - FRONTEND_OAUTH_REDIRECT=http://localhost:8080/oauth/callback
      - JWT_SECRET=hejsanhoppsan

  frontend:
    build: ./services/frontend
    command: sh -c "npm install && npm run dev"
    working_dir: /app
    ports:
      - 8080:3000
    depends_on:
      - backend
    volumes:
      - ./services/frontend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - API_URL_INTERNAL=http://backend:3000
      - NEXT_PUBLIC_API_URL=http://localhost:3000

  db:
    image: mongo:latest
    restart: unless-stopped
    volumes:
      - ./data/db:/data/db
    ports:
      - 27017:27017
    command: mongod --bind_ip_all
    environment:
      - MONGO_DATA_DIR=/data/db
